---
# tasks file for instalar.elasticsearch
- name: install the latest version of elasticsearch
  yum:
    name: elasticsearch
    state: latest

- name: Configure Elasticsearch yml.
  template:
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: root
    group: elasticsearch
    mode: 0750
  notify: restart elasticsearch

- name: Configure Elasticsearch.
  template:
    src: elasticsearch.j2
    dest: /etc/sysconfig/elasticsearch
    owner: root
    group: elasticsearch
    mode: 0750
  notify: restart elasticsearch  
  
- name: Ensure elasticsearch is started and enabled to start at boot.
  service: name=elasticsearch state=started enabled=yes