---
# tasks file for instalar.logstash
- name: install the latest version of logstash
  yum:
    name: logstash
    state: latest

# - name: Generate the logstash.service file for systemd. # yum no lo crea en el scritp.
# #  shell: /usr/share/logstash/bin/system-install /etc/logstash/startup.options systemd 
#   command: /usr/share/logstash/bin/system-install /etc/logstash/startup.options systemd 

# Disabling warnings
- name: Generate the logstash.service file for systemd. # yum no lo crea en el scritp.
  shell: /usr/share/logstash/bin/system-install /etc/logstash/startup.options systemd
  args:
    warn: False

- name: Configure openssl cnf.
  template:
    src: openssl.cnf.j2
    dest: /etc/pki/tls/openssl.cnf

- name: create cluster root ca key
  shell: >
    openssl req -config /etc/pki/tls/openssl.cnf -x509 
    -days 3650 -batch -nodes -newkey rsa:2048 
    -keyout /etc/pki/tls/private/logstash-forwarder.key 
    -out /etc/pki/tls/certs/logstash-forwarder.crt

- name: Configure filebeat-input conf.
  template:
    src: filebeat-input.conf.j2
    dest: /etc/logstash/conf.d/filebeat-input.conf

- name: Configure syslog-filter conf.
  template:
    src: syslog-filter.conf.j2
    dest: /etc/logstash/conf.d/syslog-filter.conf

- name: Configure output-elasticsearch conf.
  template:
    src: output-elasticsearch.conf.j2
    dest: /etc/logstash/conf.d/output-elasticsearch.conf

- name: Ensure logstash is started and enabled to start at boot.
  service: name=logstash state=started enabled=yes