---
# Ansible playbook for an ELK (Elasticsearch, Logstash, Kibana) logging server.
#
# @author Jeff Geerling (2014).
# Modificado @Fcastilla

#- hosts: all
#  become: true
#  tasks:
#    - import_tasks: epel/remi_epel.yml

- hosts: logs
  gather_facts: yes

#  tasks:
#    - name: Set authorized key for user challenge copying it from current user
#      authorized_key:
#        user: vagrant
#        state: present
#        key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"  
#    - name: Agregar usuario Challenge log
#      user:
#        name: challenge

  vars_files:
    - vars/main.yml

#  pre_tasks:
#    - name: upgrade all packages.
#      yum: name=* state=latest

  roles:
    - instalar.yum
    - instalar.nginx
    - instalar.elasticsearch
    - instalar.elasticsearch-curator
    - instalar.kibana
    - instalar.logstash
    - instalar.filebeat    
#    - geerlingguy.java
#    - geerlingguy.nginx
#    - geerlingguy.elasticsearch
#    - geerlingguy.elasticsearch-curator
#    - geerlingguy.kibana
#    - geerlingguy.logstash
#    - geerlingguy.logstash-forwarder

  #tasks:
  #   - name: desactivar selinux.
  #     shell: setenforce 0
  #     become: true

  #  - name: Unconditionally reboot the machine with all defaults
  #    reboot:
  # tasks:
  #   # Copy remote file (host.example.com:/tmp/somefile) into
  #   # /tmp/fetched/host.example.com/tmp/somefile on local machine
  #   - fetch:
  #       src: /etc/elasticsearch/elasticsearch.yml
  #       dest: /home/lcastilla/ChallEver_ID0/elasticsearch.yml
  #   - fetch:
  #       src: /usr/lib/systemd/system/elasticsearch.service
  #       dest: /home/lcastilla/ChallEver_ID0/elasticsearch.service
  #   - fetch:
  #       src: /etc/sysconfig/elasticsearch
  #       dest: /home/lcastilla/ChallEver_ID0/elasticsearch   
  #   - fetch:
  #       src: /etc/kibana/kibana.yml
  #       dest: /home/lcastilla/ChallEver_ID0/kibana.yml
  #   - fetch:
  #       src: /etc/nginx/nginx.conf
  #       dest: /home/lcastilla/ChallEver_ID0/nginx.conf
  #   #- fetch:
  #   #    src: /etc/nginx/conf.d/kibana.conf
  #   #    dest: /home/lcastilla/ChallEver_ID0/kibana.conf
  #   - fetch:
  #       src: /etc/pki/tls/openssl.cnf
  #       dest: /home/lcastilla/ChallEver_ID0/openssl.cnf
  #   #- fetch:
  #   #    src: /etc/logstash/conf.d/filebeat-input.conf
  #   #    dest: /home/lcastilla/ChallEver_ID0/filebeat-input.conf  
  #   - fetch:
  #       src: /etc/filebeat/filebeat.yml
  #       dest: /home/lcastilla/ChallEver_ID0/filebeat.yml              