---
# Ansible playbook for an ELK (Elasticsearch, Logstash, Kibana) logging server.
#
# @author Jeff Geerling (2014).
# Modificado @Fcastilla

- hosts: all
  become: true
  tasks:
    - import_tasks: epel/remi_epel.yml

- hosts: logs
  gather_facts: yes
  tasks:
    - name: Agregar usuario Challenge log
      user:
        name: challenge

  vars_files:
    - vars/main.yml

  pre_tasks:
    - name: upgrade all packages.
      yum: name=* state=latest

  roles:
    - geerlingguy.java
    - geerlingguy.nginx
    - geerlingguy.elasticsearch
    - geerlingguy.elasticsearch-curator
    - geerlingguy.kibana
    - geerlingguy.logstash
    - geerlingguy.logstash-forwarder
